### PR TITLE
fixing scroll for application switching.

### LINKED ISSUE #2: Extension does not work when `switch-applications` is used
When `Alt+Tab` (or any other shortcut) is configured for `switch-applications`, instead of `switch-windows`, the extension does not work, i.e., the scroll buffer is not "cleared."

Apparently, `Main.activateWindow` is not called when windows are switched using a `switch-applications` shortcut.

https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/blob/89b2669c5ed8d3e410b4e56d8e7ca1b48e6c74a2/extension.js#L24

It would be sufficient to discover what is called when a `switch-applications` shortcut is used.

This issue is similar to https://github.com/buzztaiki/gnome-shell-extension-alt-tab-move-mouse/issues/7 and mentioned at https://github.com/microsoft/vscode/issues/28795#issuecomment-1193559573.

### PR DESCRIPTION
**Pull request by vakokako**
This fixes https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/issues/2. I'm not super familiar with gnome extensions or javascript for that matter, so any suggestions would be welcomed :)

### CODE REVIEW

**Review by lucasresck — APPROVED** [review]

**Comment by lucasresck** [comment]
Hi, @vakokako, thank you very much for your contribution!

Based on my tests and on my reading of your and GNOME's code, this seems to really fix the problem. Thank you again for that.

Because this project is under GPLv3, before accepting your PR you may want to add yourself in the copyright notice.

**Comment by vakokako** [comment]
Hey, not sure how to add myself to the copyright notice

**Comment by lucasresck** [comment]
Just add another line in the beginning of `extension.js` like
```
// Copyright (C) 2022 vakokako
...
```
or similar. But only if you desire to.

**Comment by vakokako** [comment]
Sure, added it)

**Pull request merged**
