### PR TITLE
Add GNOME 46 to the list of supported shell versions

### LINKED ISSUE #35: Release for GNOME 46?
Thank you for the extension. Are there any plan to release for GNOME 46 on extensions.gnome.org? I changed the version in `metadata.json` and it works just fine.

### PR DESCRIPTION
**Pull request by matubu**
Thanks for the extension; it seems to be working as expected on NixOS 24.05 with GNOME 46 without any changes.

#35

### CODE REVIEW

**Comment by mhagnumdw** [comment]
https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/issues/35#issuecomment-2032428897

fyi: @lucasresck 

Tks!

**Comment by lucasresck** [comment]
Hi, guys, thanks for letting me know the extension is working properly.

I haven't tested GNOME 46 yet—I'll test the extension soon and merge this PR afterwards. Then, I'll update the extension on the website.

Thank you again!

**Comment by bricker** [comment]
fwiw, I'm also using this extension on GNOME 46 and have had no issues.

**Review by lucasresck — APPROVED** [review]

**Comment by lucasresck** [comment]
Hey, folks, sorry for the delay.

The PR is merged and I'll add it to the `main` branch. The updated extension should be in GNOME Extensions soon.

Thanks!

**Pull request merged**
